### PR TITLE
Added ability to not have to pass a table

### PR DESCRIPTION
**Pull request by davisdude**
I tested all the examples, and they all work

### CODE REVIEW

**Comment by adonaac** [comment]
What's the reason for these changes? They're functionally the same. I don't understand what they add.

**Comment by davisdude** [comment]
This pull request allows you to create buttons like this:
```Lua
UI.Button( 0, 0, 100, 100 )
```
In my opinion, it can be annoying to do `UI.Button( 0, 0, 100, 100, {} )` every time. 

I understand that there aren't really many use cases for this, but I thought I would suggest.

**Comment by adonaac** [comment]
You can already omit the table. settings = settings or {} ensures that the variable settings is always set to a table. So settings.something won't nil.

**Comment by davisdude** [comment]
Try making a new button without the table. It didn't work for me, at least.

**Comment by adonaac** [comment]
I forgot to add local settings = settings or {} to the very top of every object constructor. Just doing this instead of everything you did should fix it.

**Comment by davisdude** [comment]
Okay, that's fine

**Pull request closed without merging**
